# Generated by Django 4.1 on 2023-04-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doodleblue', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='owned_by',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
